# Generated by Django 3.1.4 on 2020-12-27 02:38

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencias_de_viajes',
            fields=[
                ('id_agencia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_de_operacion', models.CharField(choices=[('T', 'Tour Operator'), ('W', 'Wholesaler'), ('R', 'Ratailer'), ('M', 'Mixta')], max_length=1)),
                ('alcance_geografico', models.CharField(choices=[('I', 'Internacional'), ('N', 'Nacional'), ('L', 'Local')], max_length=1)),
                ('web', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('calle_av', models.TextField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
                ('id_ciudad', models.IntegerField()),
                ('id_pais', models.IntegerField()),
            ],
            options={
                'db_table': 'cgr_agencias_de_viajes',
                'ordering': ['id_agencia'],
            },
        ),
        migrations.CreateModel(
            name='Alojamientos',
            fields=[
                ('id_alojamiento', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ciudad', models.IntegerField()),
                ('id_pais', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'cgr_alojamientos',
                'ordering': ['id_alojamiento'],
            },
        ),
        migrations.CreateModel(
            name='Areas_de_interes',
            fields=[
                ('id_areas_de_interes', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_area_de_interes', models.CharField(max_length=30, unique=True)),
                ('descripcion_area_de_interes', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'cgr_areas_de_interes',
                'ordering': ['id_areas_de_interes'],
            },
        ),
        migrations.CreateModel(
            name='Asesores_de_viajes',
            fields=[
                ('id_asesor', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'db_table': 'cgr_asesores_de_viajes',
                'ordering': ['id_asesor'],
            },
        ),
        migrations.CreateModel(
            name='Atracciones',
            fields=[
                ('id_atraccion', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ciudad', models.IntegerField()),
                ('id_pais', models.IntegerField()),
                ('nombre_atraccion', models.CharField(max_length=30)),
                ('descripcion_atraccion', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'cgr_atracciones',
                'ordering': ['id_atraccion'],
            },
        ),
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id_banco', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cgr_bancos',
                'ordering': ['id_banco'],
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=30)),
                ('tipo_ciudad', models.CharField(choices=[('localidad', 'Localidad'), ('ciudad', 'Ciudad')], max_length=15)),
                ('descripcion_ciudad', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'cgr_ciudades',
                'ordering': ['id_ciudad'],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('doc_identidad_o_rif', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=30)),
                ('tipo_cliente', models.CharField(choices=[('natural', 'Natural'), ('juridico', 'Juridico')], max_length=10)),
                ('primer_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'cgr_clientes',
                'ordering': ['doc_identidad_o_rif'],
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=30)),
                ('region_pais', models.CharField(choices=[('EU', 'Europa'), ('AF_MO', 'Africa & Medio Oriente'), ('AU_NZ_PAC', 'Australia, Nueva Zelanda & Pacifico'), ('AS', 'Asia'), ('MEX_CEN_SUR', 'Mexico, Centro & Sur America'), ('USA_CAN_CAR', 'USA, Canada & Caribe')], max_length=15)),
                ('continente_pais', models.CharField(choices=[('Asia', 'Asica'), ('Africa', 'Africa'), ('Oceania', 'Oceania'), ('Europa', 'Europa'), ('America', 'America')], max_length=15)),
                ('nacionalidad', models.CharField(max_length=60)),
                ('descripcion_pais', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'cgr_paises',
                'ordering': ['id_pais'],
            },
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id_paquete', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_paquete', models.CharField(max_length=30)),
                ('duracion_en_dias', models.IntegerField()),
                ('descripcion_turistica', models.TextField(max_length=255)),
                ('disponible', models.BooleanField(blank=True, null=True)),
                ('numero_personas', models.IntegerField(blank=True, null=True)),
                ('id_agencia', models.ForeignKey(db_column='id_agencia', on_delete=django.db.models.deletion.CASCADE, related_name='id_agencia_pa', to='administration.agencias_de_viajes')),
            ],
            options={
                'db_table': 'cgr_paquetes',
                'ordering': ['id_agencia'],
                'unique_together': {('id_agencia', 'id_agencia')},
            },
        ),
        migrations.CreateModel(
            name='Paquetes_contrato',
            fields=[
                ('numero_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('id_paquete', models.IntegerField()),
                ('id_agencia', models.IntegerField()),
                ('id_reg_cliente', models.IntegerField()),
                ('id_reg_agencia', models.IntegerField()),
                ('presupuesto', models.IntegerField()),
                ('f_aprobacion', models.DateField()),
                ('f_emision', models.DateField()),
                ('email_validacion', models.CharField(max_length=30)),
                ('total_costo_calculado', models.IntegerField()),
                ('numero_viajeros', models.IntegerField()),
                ('f_viajes', models.DateField()),
                ('id_asesor', models.ForeignKey(blank=True, db_column='id_asesor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_asesor_paq', to='administration.asesores_de_viajes')),
                ('paquete', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.paquetes', to_fields={'id_agencia': compositefk.fields.LocalFieldValue('id_agencia')})),
            ],
            options={
                'db_table': 'cgr_paquetes_contrato',
                'ordering': ['numero_factura'],
            },
        ),
        migrations.CreateModel(
            name='Rallies',
            fields=[
                ('id_rally', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rally', models.CharField(max_length=30)),
                ('costo_participante', models.IntegerField()),
                ('f_inicio', models.DateField()),
                ('f_fin', models.DateField()),
                ('tipo_rally', models.CharField(choices=[('individual', 'Individual'), ('pareja', 'Pareja')], max_length=15)),
                ('duracion', models.IntegerField()),
                ('total_cupo_participante', models.IntegerField()),
            ],
            options={
                'db_table': 'cgr_rallies',
                'ordering': ['id_rally'],
            },
        ),
        migrations.CreateModel(
            name='Viajeros',
            fields=[
                ('id_de_identidad', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ciudad', models.IntegerField()),
                ('id_pais', models.IntegerField()),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('f_nacimiento', models.DateField()),
                ('id_paquete_contrato', models.ForeignKey(db_column='numero_factura', on_delete=django.db.models.deletion.CASCADE, related_name='id_paquete_viajeros', to='administration.paquetes_contrato')),
                ('lugar', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.ciudades', to_fields={'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais')})),
            ],
            options={
                'db_table': 'cgr_viajeros',
                'ordering': ['id_de_identidad'],
            },
        ),
        migrations.CreateModel(
            name='Puntuaciones',
            fields=[
                ('id_puntuacion', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ciudad', models.IntegerField(blank=True, null=True)),
                ('id_pais', models.IntegerField(blank=True, null=True)),
                ('id_atraccion', models.IntegerField(blank=True, null=True)),
                ('id_paquete_contrato', models.ForeignKey(blank=True, db_column='numero_factura', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_paq_cont_puntuacion', to='administration.paquetes_contrato')),
                ('id_rally', models.ForeignKey(blank=True, db_column='id_rally', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_puntuacion_rally', to='administration.rallies')),
                ('lugar', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.atracciones', to_fields={'id_atraccion': compositefk.fields.LocalFieldValue('id_atraccion'), 'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais')})),
            ],
            options={
                'db_table': 'cgr_puntuaciones',
                'ordering': ['id_puntuacion'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_proveedor', models.CharField(choices=[('exclusivo', 'Exclusivo'), ('multiagencias', 'Multiagencias')], max_length=15, verbose_name='Tipo')),
                ('id_alojamiento', models.ForeignKey(db_column='id_alojamiento', on_delete=django.db.models.deletion.CASCADE, related_name='id_alojamiento_proveedor', to='administration.alojamientos')),
            ],
            options={
                'db_table': 'cgr_proveedores',
                'ordering': ['id_proveedor'],
            },
        ),
        migrations.CreateModel(
            name='Intinerarios',
            fields=[
                ('orden', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ciudad', models.IntegerField()),
                ('id_pais', models.IntegerField()),
                ('id_agencia', models.IntegerField()),
                ('id_paquete', models.IntegerField()),
                ('tiempo_estadia', models.IntegerField()),
                ('lugar', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.ciudades', to_fields={'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais')})),
                ('paquete', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.paquetes', to_fields={'id_agencia': compositefk.fields.LocalFieldValue('id_agencia')})),
            ],
            options={
                'db_table': 'cgr_intinerarios',
                'ordering': ['orden'],
                'unique_together': {('orden', 'id_ciudad', 'id_pais', 'id_agencia', 'id_paquete')},
            },
        ),
        migrations.CreateModel(
            name='Instrumentos_de_pago',
            fields=[
                ('id_instrumento', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('tipo_instrumento', models.CharField(choices=[('TDC', 'Tarjeta de Credito'), ('zelle', 'Zelle'), ('TDD', 'Tarjeta de Debito'), ('ctabanco', 'Cuanta Bancaria')], max_length=30)),
                ('numero_zelle', models.IntegerField(blank=True, null=True)),
                ('email_zelle', models.CharField(blank=True, max_length=15, null=True)),
                ('doc_identidad_cliente', models.ForeignKey(db_column='doc_identidad_o_rif', on_delete=django.db.models.deletion.CASCADE, related_name='id_doc_iden_cli_ins', to='administration.clientes')),
                ('id_banco', models.ForeignKey(blank=True, db_column='id_banco', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_banco_inst', to='administration.bancos')),
            ],
            options={
                'db_table': 'cgr_instrumentos_de_pago',
                'ordering': ['id_instrumento'],
                'unique_together': {('id_instrumento', 'doc_identidad_cliente')},
            },
        ),
        migrations.CreateModel(
            name='Detalles_servicios',
            fields=[
                ('id_detalles_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('id_intinerario', models.IntegerField()),
                ('id_paquete', models.IntegerField()),
                ('id_agencia', models.IntegerField()),
                ('id_ciudad', models.IntegerField()),
                ('id_pais', models.IntegerField()),
                ('tipo_detalle', models.CharField(choices=[('boleto_tren', 'Boleto de tren'), ('boleto_autobus', 'Boleto de Autobus'), ('cama_alq', 'Cama de alquiler'), ('otro', 'otros'), ('boleto_avion', 'Boleto de avion'), ('alojamiento', 'Alojamiento')], max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('comida', models.BooleanField(blank=True, null=True)),
                ('paquete', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.intinerarios', to_fields={'id_agencia': compositefk.fields.LocalFieldValue('id_agencia'), 'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais'), 'id_paquete': compositefk.fields.LocalFieldValue('id_paquete'), 'orden': compositefk.fields.LocalFieldValue('id_intinerario')})),
            ],
            options={
                'db_table': 'cgr_Detalle_servicios',
                'ordering': ['id_detalles_servicio'],
                'unique_together': {('id_intinerario', 'id_ciudad', 'id_pais', 'id_agencia', 'id_paquete', 'id_detalles_servicio')},
            },
        ),
        migrations.AddField(
            model_name='ciudades',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, related_name='id_pais_ciu', to='administration.paises'),
        ),
        migrations.CreateModel(
            name='Circuitos',
            fields=[
                ('orden_circuito', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ciudad', models.IntegerField()),
                ('id_pais', models.IntegerField()),
                ('maxdias', models.IntegerField()),
                ('id_rally', models.ForeignKey(db_column='id_rally', on_delete=django.db.models.deletion.CASCADE, related_name='id_rally_cir', to='administration.rallies')),
                ('lugar', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.ciudades', to_fields={'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais')})),
            ],
            options={
                'db_table': 'cgr_circuitos',
                'ordering': ['orden_circuito'],
                'unique_together': {('orden_circuito', 'id_rally', 'id_ciudad', 'id_pais')},
            },
        ),
        migrations.CreateModel(
            name='Calendarios_anuales',
            fields=[
                ('f_salida', models.DateField(primary_key=True, serialize=False)),
                ('id_paquete', models.IntegerField()),
                ('id_agencia', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cgr_calendarios_anuales',
                'ordering': ['f_salida'],
                'unique_together': {('f_salida', 'id_paquete', 'id_agencia')},
            },
        ),
        migrations.AddField(
            model_name='atracciones',
            name='lugar',
            field=compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.ciudades', to_fields={'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais')}),
        ),
        migrations.AddField(
            model_name='alojamientos',
            name='lugar',
            field=compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.ciudades', to_fields={'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais')}),
        ),
        migrations.AddField(
            model_name='agencias_de_viajes',
            name='lugar',
            field=compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.ciudades', to_fields={'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais')}),
        ),
        migrations.CreateModel(
            name='Registro_viajeros',
            fields=[
                ('id_agencia', models.ForeignKey(db_column='id_agencia', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='id_agencia_reg_via', serialize=False, to='administration.agencias_de_viajes')),
                ('f_registro', models.DateField()),
                ('nro_registro', models.IntegerField()),
                ('id_viajero', models.ForeignKey(db_column='id_de_identidad', on_delete=django.db.models.deletion.CASCADE, related_name='id_viajero_reg_via', to='administration.viajeros')),
            ],
            options={
                'db_table': 'cgr_registro_viajeros',
                'ordering': ['id_viajero'],
                'unique_together': {('id_viajero', 'id_agencia')},
            },
        ),
        migrations.CreateModel(
            name='Registro_clientes',
            fields=[
                ('id_cliente', models.ForeignKey(db_column='doc_identidad_o_rif', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='id_clientes_registro', serialize=False, to='administration.clientes')),
                ('f_registro', models.DateField()),
                ('numero_registro', models.IntegerField()),
                ('id_agencia', models.ForeignKey(db_column='id_agencia', on_delete=django.db.models.deletion.CASCADE, related_name='id_agencia_registro', to='administration.agencias_de_viajes')),
            ],
            options={
                'db_table': 'cgr_registro_clientes',
                'ordering': ['id_cliente'],
                'unique_together': {('id_agencia', 'id_cliente')},
            },
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id_premio', models.IntegerField(primary_key=True, serialize=False)),
                ('posicion', models.IntegerField(choices=[(1, '1er'), (2, '2do'), (3, '3ro')])),
                ('descripcion_premio', models.TextField(max_length=255)),
                ('id_rally', models.ForeignKey(db_column='id_rally', on_delete=django.db.models.deletion.CASCADE, related_name='id_rally_pre', to='administration.rallies')),
            ],
            options={
                'db_table': 'cgr_premios',
                'ordering': ['id_premio'],
                'unique_together': {('id_premio', 'id_rally')},
            },
        ),
        migrations.CreateModel(
            name='Precios_paquetes',
            fields=[
                ('f_inicio', models.DateField(primary_key=True, serialize=False)),
                ('id_paquete', models.IntegerField()),
                ('id_agencia', models.IntegerField()),
                ('f_fin', models.DateField(blank=True, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('paquete', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.paquetes', to_fields={'id_agencia': compositefk.fields.LocalFieldValue('id_agencia')})),
            ],
            options={
                'db_table': 'cgr_precios_paquetes',
                'ordering': ['f_inicio'],
                'unique_together': {('f_inicio', 'id_paquete', 'id_agencia')},
            },
        ),
        migrations.AddField(
            model_name='paquetes_contrato',
            name='registro',
            field=compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.registro_clientes', to_fields={'id_agencia': compositefk.fields.LocalFieldValue('id_reg_agencia'), 'id_cliente': compositefk.fields.LocalFieldValue('id_reg_cliente')}),
        ),
        migrations.CreateModel(
            name='PAI_VIA',
            fields=[
                ('id_viajero', models.ForeignKey(db_column='id_de_identidad', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='id_viajero_via', serialize=False, to='administration.viajeros')),
                ('nro_de_pasaporte', models.IntegerField()),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, related_name='id_pais_via', to='administration.paises')),
            ],
            options={
                'db_table': 'cgr_paq_via',
                'ordering': ['id_viajero'],
            },
        ),
        migrations.CreateModel(
            name='ITN_ATR',
            fields=[
                ('id_intinerario', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ciudad', models.IntegerField()),
                ('id_pais', models.IntegerField()),
                ('id_agencia', models.IntegerField()),
                ('id_paquete', models.IntegerField()),
                ('id_atraccion', models.IntegerField()),
                ('id_ciudad_at', models.IntegerField()),
                ('id_pais_at', models.IntegerField()),
                ('orden_visita', models.IntegerField()),
                ('lugar', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.atracciones', to_fields={'id_atraccion': compositefk.fields.LocalFieldValue('id_atraccion'), 'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad_at'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais_at')})),
                ('paquete', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.intinerarios', to_fields={'id_agencia': compositefk.fields.LocalFieldValue('id_agencia'), 'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais'), 'id_paquete': compositefk.fields.LocalFieldValue('id_paquete'), 'orden': compositefk.fields.LocalFieldValue('id_intinerario')})),
            ],
            options={
                'db_table': 'cgr_itn_atr',
                'ordering': ['id_intinerario'],
                'unique_together': {('id_intinerario', 'id_ciudad', 'id_pais', 'id_agencia', 'id_paquete', 'id_atraccion', 'id_ciudad_at', 'id_pais_at')},
            },
        ),
        migrations.CreateModel(
            name='Formas_de_pago',
            fields=[
                ('id_instrumento', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('tipo_forma_de_pago', models.CharField(blank=True, choices=[('parcial', 'Parcial'), ('cuotas', 'Cuotas')], max_length=30, null=True)),
                ('id_paquete_contrato', models.ForeignKey(db_column='numero_factura', on_delete=django.db.models.deletion.CASCADE, related_name='id_paquete_contrato', to='administration.paquetes_contrato')),
                ('pago_instrumento', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.instrumentos_de_pago', to_fields={'doc_identidad_cliente': compositefk.fields.LocalFieldValue('id_cliente'), 'id_instrumento': compositefk.fields.LocalFieldValue('id_instrumento')})),
            ],
            options={
                'db_table': 'cgr_formas_de_pago',
                'ordering': ['id_instrumento'],
                'unique_together': {('id_instrumento', 'id_cliente', 'id_paquete_contrato')},
            },
        ),
        migrations.CreateModel(
            name='Especializaciones',
            fields=[
                ('id_especializacion', models.IntegerField(primary_key=True, serialize=False)),
                ('id_atraccion', models.IntegerField()),
                ('id_ciudad', models.IntegerField()),
                ('id_pais', models.IntegerField()),
                ('id_paquete', models.IntegerField()),
                ('id_agencia_paquete', models.IntegerField()),
                ('comentarios', models.TextField(max_length=255)),
                ('id_agencia', models.ForeignKey(db_column='id_agencia', on_delete=django.db.models.deletion.CASCADE, related_name='id_agencia_es', to='administration.agencias_de_viajes')),
                ('id_areas_de_interes', models.ForeignKey(db_column='id_areas_de_interes', on_delete=django.db.models.deletion.CASCADE, related_name='id_area_es', to='administration.areas_de_interes')),
                ('id_asesor', models.ForeignKey(db_column='id_asesor', on_delete=django.db.models.deletion.CASCADE, related_name='id_asesor_es', to='administration.asesores_de_viajes')),
                ('lugar', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.atracciones', to_fields={'id_atraccion': compositefk.fields.LocalFieldValue('id_atraccion'), 'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais')})),
                ('paquete', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.paquetes', to_fields={'id_agencia': compositefk.fields.LocalFieldValue('id_agencia_paquete')})),
            ],
            options={
                'db_table': 'cgr_especializaciones',
                'ordering': ['id_especializacion'],
                'unique_together': {('id_areas_de_interes', 'id_especializacion')},
            },
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id_descuento', models.IntegerField(primary_key=True, serialize=False)),
                ('f_inicio', models.DateField()),
                ('tipo_descuento', models.CharField(choices=[('descnino', 'Descuento niño'), ('adultos', 'Adultos'), ('general', 'General'), ('viajerosgratis', 'Viaje gratis'), ('otro', 'Otro')], max_length=20)),
                ('f_fin', models.DateField(blank=True, null=True)),
                ('cant_per_gratis', models.IntegerField(blank=True, null=True)),
                ('porcentaje', models.IntegerField(blank=True, null=True)),
                ('id_agencia', models.ForeignKey(db_column='id_agencia', on_delete=django.db.models.deletion.CASCADE, related_name='id_agencia_des', to='administration.agencias_de_viajes')),
            ],
            options={
                'db_table': 'cgr_descuentos',
                'ordering': ['id_descuento'],
                'unique_together': {('id_descuento', 'id_agencia')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ciudades',
            unique_together={('id_ciudad', 'id_pais')},
        ),
        migrations.AlterUniqueTogether(
            name='atracciones',
            unique_together={('id_ciudad', 'id_pais', 'id_atraccion')},
        ),
        migrations.CreateModel(
            name='ATR_CIR',
            fields=[
                ('id_atraccion', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ciudad_at', models.IntegerField()),
                ('id_pais_at', models.IntegerField()),
                ('id_circuito', models.IntegerField()),
                ('id_rally_cir', models.IntegerField()),
                ('id_ciudad_cir', models.IntegerField()),
                ('id_pais_cir', models.IntegerField()),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('lugar', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.atracciones', to_fields={'id_atraccion': compositefk.fields.LocalFieldValue('id_atraccion'), 'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad_at'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais_at')})),
                ('recorrido', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.circuitos', to_fields={'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad_cir'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais_cir'), 'id_rally': compositefk.fields.LocalFieldValue('id_rally_cir'), 'orden_circuito': compositefk.fields.LocalFieldValue('id_circuito')})),
            ],
            options={
                'db_table': 'cgr_atr_cir',
                'ordering': ['id_atraccion'],
                'unique_together': {('id_atraccion', 'id_ciudad_at', 'id_pais_at', 'id_circuito', 'id_rally_cir', 'id_ciudad_cir', 'id_pais_cir')},
            },
        ),
        migrations.CreateModel(
            name='ALO_DET',
            fields=[
                ('id_detalle_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('id_intinerario', models.IntegerField()),
                ('id_paquete', models.IntegerField()),
                ('id_agencia', models.IntegerField()),
                ('id_ciudad', models.IntegerField()),
                ('id_pais', models.IntegerField()),
                ('detalle', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.detalles_servicios', to_fields={'id_agencia': compositefk.fields.LocalFieldValue('id_agencia'), 'id_ciudad': compositefk.fields.LocalFieldValue('id_ciudad'), 'id_detalles_servicio': compositefk.fields.LocalFieldValue('id_detalle_servicio'), 'id_intinerario': compositefk.fields.LocalFieldValue('id_intinerario'), 'id_pais': compositefk.fields.LocalFieldValue('id_pais'), 'id_paquete': compositefk.fields.LocalFieldValue('id_paquete')})),
                ('id_alojamiento', models.ForeignKey(db_column='id_alojamiento', on_delete=django.db.models.deletion.CASCADE, related_name='id_clientes_ALO', to='administration.alojamientos')),
            ],
            options={
                'db_table': 'cgr_alo_det',
                'ordering': ['id_detalle_servicio'],
                'unique_together': {('id_intinerario', 'id_ciudad', 'id_pais', 'id_agencia', 'id_paquete', 'id_alojamiento', 'id_detalle_servicio')},
            },
        ),
        migrations.CreateModel(
            name='AGE_AGE',
            fields=[
                ('id_agencia', models.IntegerField(primary_key=True, serialize=False)),
                ('id_socio', models.IntegerField()),
                ('f_inicio', models.DateField()),
                ('f_fin', models.DateField(blank=True, null=True)),
                ('colegas', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.agencias_de_viajes', to_fields={'id_agencia': compositefk.fields.LocalFieldValue('id_socio')})),
            ],
            options={
                'db_table': 'cgr_age_age',
                'ordering': ['id_agencia'],
                'unique_together': {('id_agencia', 'id_socio')},
            },
        ),
        migrations.CreateModel(
            name='PRO_AGE',
            fields=[
                ('id_agencia', models.ForeignKey(db_column='id_agencia', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='id_agencia_PA', serialize=False, to='administration.agencias_de_viajes')),
                ('f_inicio', models.DateField()),
                ('f_fin', models.DateField(blank=True, null=True)),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='id_proveedor_PA', to='administration.proveedores')),
            ],
            options={
                'db_table': 'cgr_pro_age',
                'ordering': ['id_agencia'],
                'unique_together': {('id_agencia', 'id_proveedor')},
            },
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id_partipante', models.IntegerField(primary_key=True, serialize=False)),
                ('id_via_agencia', models.IntegerField(blank=True, null=True)),
                ('id_via_viajero', models.IntegerField(blank=True, null=True)),
                ('id_cli_cliente', models.IntegerField(blank=True, null=True)),
                ('id_cli_agencia', models.IntegerField(blank=True, null=True)),
                ('equipo', models.BinaryField(blank=True, null=True)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('id_rally', models.ForeignKey(db_column='id_rally', on_delete=django.db.models.deletion.CASCADE, related_name='id_participantes_rally', to='administration.rallies')),
                ('cliente', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.registro_clientes', to_fields={'id_agencia': compositefk.fields.LocalFieldValue('id_cli_agencia'), 'id_cliente': compositefk.fields.LocalFieldValue('id_cli_cliente')})),
                ('viajero', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.registro_viajeros', to_fields={'id_agencia': compositefk.fields.LocalFieldValue('id_via_agencia'), 'id_viajero': compositefk.fields.LocalFieldValue('id_via_viajero')})),
            ],
            options={
                'db_table': 'cgr_participantes',
                'ordering': ['id_partipante'],
                'unique_together': {('id_rally', 'id_partipante')},
            },
        ),
        migrations.CreateModel(
            name='Detalle_viajeros',
            fields=[
                ('id_viajero', models.IntegerField(primary_key=True, serialize=False)),
                ('id_agencia', models.IntegerField()),
                ('id_paquete_contrato', models.ForeignKey(db_column='numero_factura', on_delete=django.db.models.deletion.CASCADE, related_name='id_paq_cont_det', to='administration.paquetes_contrato')),
                ('traveler', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='administration.registro_viajeros', to_fields={'id_agencia': compositefk.fields.LocalFieldValue('id_agencia'), 'id_viajero': compositefk.fields.LocalFieldValue('id_viajero')})),
            ],
            options={
                'db_table': 'cgr_detalle_viajeros',
                'ordering': ['id_viajero'],
                'unique_together': {('id_viajero', 'id_agencia', 'id_paquete_contrato')},
            },
        ),
        migrations.CreateModel(
            name='Cupos',
            fields=[
                ('id_agencia', models.ForeignKey(db_column='id_agencia', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='id_agencia_cupos', serialize=False, to='administration.agencias_de_viajes')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('id_rally', models.ForeignKey(db_column='id_rally', on_delete=django.db.models.deletion.CASCADE, related_name='id_rally_cupos', to='administration.rallies')),
            ],
            options={
                'db_table': 'cgr_cupo',
                'ordering': ['id_agencia'],
                'unique_together': {('id_agencia', 'id_rally')},
            },
        ),
    ]
